fix: Don't duplicate error messages in logs (#3619)
There's an issue with the automatic logging of OperatorErrorSchema from
CarbideError: we were logging both the error itself and the inner
schema.text field, but both resolve to the same string.

In addition, logging CarbideError at the moment it's converted to a
tonic::Status is a bit of a hacky approach, as it emits logs even if the
request isn't complete yet (maybe the error will be handled, etc.) Plus,
the actual error itself is already being logged by our custom logfmt
layer which logs the moment a request span is closed, so it's duplicated
on two levels.

Fix these and more issues:

- Don't automatically log a CarbideError when it's converted to a
tonic::Status, instead, pack the CarbideError inside the tonic::Status
through tonic::Status::set_source(carbide_error).

- Then, our existing LogService layer can use
`result.extensions().get::<tonic::Status>()` to get the Status object
from the response, then get its source, and if it's a CarbideError, it
can log it then. Particularly, we don't add an additional
tracing::error! statement or anything, but instead just add the fields
we want to the existing span we're already logging on. This means the
error code shows up as `nico_error_code=NICO-API-500`, the mitigation
shows up as `nico_mitigation=...`, etc, all on the same log line we're
already logging at the end of each request.

- Instead of Backtrace::capture(), use Location::caller(), which gets
the source location of just the caller. It has the advantage of working
even if RUST_BACKTRACE is not enabled, and doesn't need the expensive
work of gathering a whole backtrace just to find who called the
function. We can use #[track_caller] to ensure that we get the caller's
location instead of ours.

This cuts down on the duplicate logging and puts the additional
information we want into the log lines that are already happening.

## Related issues

## Type of Change
- [ ] **Add** - New feature or capability
- [ ] **Change** - Changes in existing functionality
- [X] **Fix** - Bug fixes
- [ ] **Remove** - Removed features or deprecated functionality
- [ ] **Internal** - Internal changes (refactoring, tests, docs, etc.)

## Breaking Changes
- [ ] **This PR contains breaking changes**

## Testing
- [ ] Unit tests added/updated
- [ ] Integration tests added/updated
- [X] Manual testing performed
- [ ] No testing required (docs, internal refactor, etc.)

## Additional Notes